name: Pull Request Check
on: pull_request
jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    # - uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    # - name: Use Node.js 16
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '16'
    # - run: npm install
    # - run: npm run test-sonar
    # - name: Upload lcov code coverage
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: coverage
    #     path: coverage
    #     retention-days: 1

  # quality-gate:
  #   name: quality-gate
  #   needs: unit-test
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0
  #   - name: Download lcov code coverage
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: coverage
  #       path: coverage
  #   - name: Sonar Scan
  #     uses: sonarsource/sonarqube-scan-action@v1.0.0
  #     env:
  #       SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  #       SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
  #   - name: Quality Gate Check
  #     uses: sonarsource/sonarqube-quality-gate-action@v1.0.0
  #     timeout-minutes: 5
  #     env:
  #      SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
